// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGXdY32YK6FcqlOea9QsRQ5aou7zSa27Y',
    appId: '1:182321887917:web:f98b5a71b8e326df556424',
    messagingSenderId: '182321887917',
    projectId: 'ecommerce-f854a',
    authDomain: 'ecommerce-f854a.firebaseapp.com',
    storageBucket: 'ecommerce-f854a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPjUcDlMNW_OIfK1L1fQJn6l7ARzmBl0s',
    appId: '1:182321887917:android:1712d5560cc5c300556424',
    messagingSenderId: '182321887917',
    projectId: 'ecommerce-f854a',
    storageBucket: 'ecommerce-f854a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB00SOf3qlBKHQdJFTYHjJxLmTF9yRycs',
    appId: '1:182321887917:ios:07d43ba93430a91e556424',
    messagingSenderId: '182321887917',
    projectId: 'ecommerce-f854a',
    storageBucket: 'ecommerce-f854a.appspot.com',
    iosClientId: '182321887917-rdpr8pkebc5ht6reev2nmvi5s0poj7eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB00SOf3qlBKHQdJFTYHjJxLmTF9yRycs',
    appId: '1:182321887917:ios:0f59fa14190bf6e0556424',
    messagingSenderId: '182321887917',
    projectId: 'ecommerce-f854a',
    storageBucket: 'ecommerce-f854a.appspot.com',
    iosClientId: '182321887917-u5n4gov9a4pk80vk5i6p8ev297iajlju.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop.RunnerTests',
  );
}
